---
- name: Install Ruby && Bundler
  hosts: all
  become: true
  gather_facts: no

  tasks:
  - name: Install python for Ansible
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    changed_when: False

  # Установим в цикле все зависимости
  - name: Install ruby and rubygems and required packages
    apt: "name={{ item }} state=present"
    with_items:
      - ruby-full
      - ruby-bundler
      - build-essential
      - git
