---
- name: Install MongoDB 3.2
  hosts: all
  become: true
  gather_facts: no
  pre_tasks:
    - name: 'update apt'
      raw: sudo apt update
    - name: 'sleep'
      raw: sleep 10
    - name: 'install python2'
      raw: sudo apt-get -y install python
  tasks:
  # Добавим ключ репозитория для последующей работы с ним
  - name: Add APT key
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com

  # Подключаем репозиторий с пакетами mongodb
  - name: Add APT repository
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  # Выполним установку пакета
  - name: Install mongodb package
    apt:
      name: mongodb-org
      state: present
      force: yes

  # Включаем сервис
  - name: Configure service supervisor
    systemd:
      name: mongod
      enabled: yes
