---
- name: Install Ruby && Bundler
  hosts: all
  become: true
  gather_facts: no
  pre_tasks:
    - name: 'update apt'
      raw: sudo apt update
    - name: 'sleep'
      raw: sleep 10
    - name: 'install python2'
      raw: sudo apt-get -y install python
  tasks:
  # Установим в цикле все зависимости
  - name: Install ruby and rubygems and required packages
    apt: "name={{ item }} state=present"
    with_items:
      - ruby-full
      - ruby-bundler
      - build-essential
      - git
